# Generated by Django 4.1 on 2022-09-14 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
