# Generated by Django 4.1 on 2022-09-14 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
        migrations.AddField(
            model_name='item',
            name='ora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ziua',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
